//! Named colour palettes. Each one is rendered through every pattern.
//!
//! `stops` run from the "light / surface" end to the "deep" end; `base` is a dim
//! background for patterns that need one; `accent` is a highlight colour.
//! Colours are chosen for LEDs: saturated, and never so dark they read as "off".

use keylume_proto::Rgb;

pub struct Palette {
    pub id: &'static str,
    pub name: &'static str,
    pub family: &'static str,
    pub description: &'static str,
    pub tags: &'static [&'static str],
    pub stops: Vec<Rgb>,
    pub base: Rgb,
    pub accent: Rgb,
    /// Render only these patterns (None: every pattern).
    pub only: Option<&'static [&'static str]>,
}

fn h(s: &str) -> Rgb {
    s.parse().expect("palette colours are valid hex")
}

#[allow(clippy::too_many_arguments)] // a table row: every field is named in the data below
pub(crate) fn pal(
    id: &'static str,
    name: &'static str,
    family: &'static str,
    description: &'static str,
    tags: &'static [&'static str],
    stops: &[&str],
    base: &str,
    accent: &str,
) -> Palette {
    Palette { id, name, family, description, tags, stops: stops.iter().map(|s| h(s)).collect(), base: h(base), accent: h(accent), only: None }
}

/// Patterns that suit the Counter-Strike palettes.
pub const CS_PATTERNS: &[&str] = &["loadout", "crosshair", "gamer", "horizon", "bloom", "marble", "stained-glass", "tidal", "frame", "split"];

pub fn all() -> Vec<Palette> {
    let cs = |p: Palette| Palette { only: Some(CS_PATTERNS), ..p };
    vec![
        // ---- CS2 sides & maps (a CS-flavoured set of patterns each) ------------
        cs(pal(
            "ct-side",
            "CT Side",
            "CS2",
            "Counter-Terrorist navy and steel blue with a gold defuse-kit accent",
            &["blue", "gaming", "cs"],
            &["#b8d4ff", "#5b8cff", "#2a4fd0", "#13287a"],
            "#0a1640",
            "#ffd24a",
        )),
        cs(pal(
            "t-side",
            "T Side",
            "CS2",
            "Terrorist amber and rust with a blue accent",
            &["warm", "gaming", "cs"],
            &["#ffe08a", "#ffb030", "#d86a10", "#6a2a05"],
            "#1f0e04",
            "#00a0ff",
        )),
        cs(pal(
            "dust",
            "Desert Dust",
            "CS2",
            "Dust II sandstone and a sky-blue sightline",
            &["warm", "gaming", "cs"],
            &["#f4dca0", "#d8b070", "#b08040", "#6a4a20"],
            "#1f1408",
            "#00a0ff",
        )),
        // ---- Red & pink ------------------------------------------------------------
        pal(
            "crimson",
            "Crimson",
            "Red",
            "Deep crimson and cherry red",
            &["red", "bold"],
            &["#ff6060", "#ff1030", "#c00020", "#6a0010"],
            "#1a0004",
            "#ffd0d0",
        ),
        pal(
            "blood-moon",
            "Blood Moon",
            "Red",
            "An eclipse glow: amber rim, blood-red body",
            &["red", "warm", "dark"],
            &["#ffcf80", "#ff5a1f", "#d0001b", "#5a0010"],
            "#160004",
            "#ffe8b0",
        ),
        pal(
            "rose",
            "Rose Garden",
            "Red",
            "Rose petals from blush to deep rose",
            &["pink", "red", "soft"],
            &["#ffd0dc", "#ff8aa8", "#ff3d6e", "#b0103c"],
            "#1a0610",
            "#ffffff",
        ),
        pal(
            "bubblegum",
            "Bubblegum",
            "Pink",
            "Hot bubblegum and candy pink",
            &["pink", "bright"],
            &["#ffd6f5", "#ff8ae2", "#ff3fc8", "#b0108a"],
            "#1a0414",
            "#ffffff",
        ),
        pal(
            "magenta",
            "Hot Magenta",
            "Pink",
            "Pure magenta turned all the way up",
            &["pink", "purple", "neon"],
            &["#ffb0ff", "#ff40ff", "#d000d0", "#700070"],
            "#180018",
            "#ffffff",
        ),
        pal(
            "peach",
            "Peach",
            "Pink",
            "Soft peach and coral",
            &["pink", "warm", "pastel"],
            &["#ffe6d6", "#ffb08a", "#ff7a59", "#d9443a"],
            "#1a0a06",
            "#ffffff",
        ),
        // ---- Orange & yellow ---------------------------------------------------------
        pal(
            "tangerine",
            "Tangerine",
            "Orange",
            "Juicy tangerine and burnt orange",
            &["orange", "warm"],
            &["#ffd08a", "#ff9a2e", "#ff6a00", "#b83c00"],
            "#1a0a00",
            "#fff4d0",
        ),
        pal(
            "amber",
            "Amber",
            "Orange",
            "Warm amber, like light through honey",
            &["orange", "yellow", "warm"],
            &["#ffe9a0", "#ffc233", "#ff9900", "#a86000"],
            "#1a1000",
            "#ffffff",
        ),
        pal(
            "lemonade",
            "Lemonade",
            "Yellow",
            "Sunny lemon yellow",
            &["yellow", "bright"],
            &["#fffbd0", "#fff35c", "#ffd000", "#c89a00"],
            "#161200",
            "#ffffff",
        ),
        pal(
            "gold",
            "Gold Rush",
            "Yellow",
            "Polished gold with a bright glint",
            &["yellow", "gold", "warm"],
            &["#fff0b0", "#ffd24a", "#e0a800", "#8a6000"],
            "#140e00",
            "#ffffff",
        ),
        // ---- Green (more) --------------------------------------------------------------
        pal(
            "jade",
            "Jade",
            "Green",
            "Carved jade from pale mint to deep green",
            &["green", "gem"],
            &["#b8ffd8", "#3dffa0", "#00c878", "#006840"],
            "#001a0e",
            "#ffffff",
        ),
        pal(
            "lime",
            "Lime Light",
            "Green",
            "Zesty lime and electric chartreuse",
            &["green", "yellow", "neon"],
            &["#f0ff9a", "#c8ff2e", "#7ad600", "#3a7a00"],
            "#0c1400",
            "#ffffff",
        ),
        // ---- Neutral -------------------------------------------------------------------
        pal(
            "monochrome",
            "Monochrome",
            "Soft",
            "Pure white to soft grey: clean and calm",
            &["white", "minimal"],
            &["#ffffff", "#d0d0d0", "#909090", "#505050"],
            "#141414",
            "#ffffff",
        ),
        pal(
            "warm-white",
            "Warm White",
            "Soft",
            "Cosy warm white, like a desk lamp",
            &["white", "warm", "minimal"],
            &["#fff4e0", "#ffd9a0", "#ffb870", "#c07830"],
            "#1a1208",
            "#ffffff",
        ),
        // ---- Trippy ------------------------------------------------------------
        pal(
            "acid",
            "Acid",
            "Trippy",
            "Acid yellow, radioactive green, aqua and hot magenta",
            &["trippy", "neon"],
            &["#fff200", "#00ff60", "#00ffe0", "#ff00c8"],
            "#0a0014",
            "#ffffff",
        ),
        pal(
            "psychedelic",
            "Psychedelic",
            "Trippy",
            "A 1967 poster: every colour, turned up",
            &["trippy", "rainbow"],
            &["#ff0080", "#ff8000", "#ffff00", "#00ff80", "#0080ff", "#8000ff"],
            "#100010",
            "#ffffff",
        ),
        pal(
            "ultraviolet",
            "Ultraviolet",
            "Trippy",
            "Blacklight violet sliding into deep UV",
            &["trippy", "purple"],
            &["#e0a0ff", "#b000ff", "#6000ff", "#2000a0"],
            "#0a0020",
            "#00ffff",
        ),
        pal(
            "oil-slick",
            "Oil Slick",
            "Trippy",
            "Petrol rainbow on wet tarmac: teal, blue, violet, pink, gold",
            &["trippy", "iridescent"],
            &["#00ffc8", "#0060ff", "#a000ff", "#ff00a0", "#ffb000"],
            "#050510",
            "#ffffff",
        ),
        pal(
            "holographic",
            "Holographic",
            "Trippy",
            "Pale iridescent foil: mint, periwinkle, lilac, rose",
            &["trippy", "pastel", "iridescent"],
            &["#c0fff4", "#b0c8ff", "#f0b0ff", "#ffd0e8"],
            "#101020",
            "#ffffff",
        ),
        pal(
            "blacklight",
            "Blacklight",
            "Trippy",
            "UV-reactive lime and magenta under a blacklight",
            &["trippy", "neon"],
            &["#d0ff00", "#ff00ff", "#7000ff", "#1000a0"],
            "#08001a",
            "#00ffff",
        ),
        pal(
            "hypnotic",
            "Hypnotic",
            "Trippy",
            "Stark white, magenta and electric blue for maximum contrast",
            &["trippy", "contrast", "blue"],
            &["#ffffff", "#ff00ff", "#0040ff", "#2a0aa0"],
            "#0c0630",
            "#ffffff",
        ),
        pal(
            "candy",
            "Candy Shop",
            "Trippy",
            "Bubblegum, lemon drop, spearmint and blue raspberry",
            &["trippy", "pastel"],
            &["#ff6ec7", "#ffd166", "#06d6a0", "#118ab2"],
            "#140818",
            "#ffffff",
        ),
        pal(
            "northern-lights",
            "Northern Lights",
            "Trippy",
            "Green curtains of aurora rippling into violet",
            &["trippy", "green", "blue"],
            &["#a0ff60", "#00ffa0", "#00c0ff", "#8040ff"],
            "#020a18",
            "#e0fff0",
        ),
        // ---- Blue --------------------------------------------------------------
        pal(
            "deep-ocean",
            "Deep Ocean",
            "Blue",
            "Sunlit aqua fading into the abyss",
            &["blue", "ocean"],
            &["#00fff0", "#00c8ff", "#0080ff", "#0030f0", "#0012b0"],
            "#001040",
            "#00ffff",
        ),
        pal(
            "arctic",
            "Arctic",
            "Blue",
            "Ice white melting into cold cobalt",
            &["blue", "ice"],
            &["#ddf6ff", "#7fdbff", "#0096ff", "#0040e0", "#0018a0"],
            "#001455",
            "#ffffff",
        ),
        pal(
            "sapphire",
            "Sapphire",
            "Blue",
            "Polished sapphire from cyan sparkle to royal depth",
            &["blue", "gem"],
            &["#00d8ff", "#0070ff", "#0030e0", "#001aa0"],
            "#000c50",
            "#7df9ff",
        ),
        pal(
            "electric",
            "Electric Blue",
            "Blue",
            "High-voltage cyan into pure electric blue",
            &["blue", "neon"],
            &["#00ffff", "#00a0ff", "#2040ff"],
            "#000a40",
            "#00ffff",
        ),
        pal(
            "midnight",
            "Midnight",
            "Blue",
            "Late-night navy with a cool blue glow",
            &["blue", "dark"],
            &["#5a78ff", "#2f45e0", "#1a28a8", "#101a78"],
            "#070d40",
            "#00e5ff",
        ),
        pal(
            "glacier",
            "Glacier",
            "Blue",
            "Bright glacier ice over deep crevasse blue",
            &["blue", "ice", "bright"],
            &["#ffffff", "#bdebff", "#5cc8ff", "#1e90ff"],
            "#0a2050",
            "#ffffff",
        ),
        pal(
            "cobalt",
            "Royal Cobalt",
            "Blue",
            "Regal cobalt and royal blue",
            &["blue", "royal"],
            &["#4169e1", "#1e3cff", "#0010d0", "#000890"],
            "#000530",
            "#8ab4ff",
        ),
        pal(
            "cyber-cyan",
            "Cyber Cyan",
            "Blue",
            "Neon cyan straight out of a cyberpunk HUD",
            &["blue", "neon", "cyber"],
            &["#00ffe0", "#00e5ff", "#00b0ff", "#0060ff"],
            "#001830",
            "#ffffff",
        ),
        pal(
            "storm",
            "Storm Front",
            "Blue",
            "Slate thunderclouds with lightning-blue edges",
            &["blue", "moody"],
            &["#a0c4ff", "#5078ff", "#2a3fbf", "#141e60"],
            "#070c28",
            "#e0f0ff",
        ),
        pal(
            "blue-hour",
            "Blue Hour",
            "Blue",
            "The quiet blue after sunset, a touch of violet",
            &["blue", "violet"],
            &["#7ab8ff", "#3d6bff", "#3b2bd0", "#20108a"],
            "#0a0630",
            "#b0d0ff",
        ),
        pal(
            "neptune",
            "Neptune",
            "Blue",
            "The ice giant's deep azure bands",
            &["blue", "space"],
            &["#7fd4ff", "#2f8cff", "#1a4fe0", "#0d2a9a"],
            "#050f3a",
            "#c8f0ff",
        ),
        pal(
            "cerulean",
            "Cerulean",
            "Blue",
            "Clear summer-sky cerulean",
            &["blue", "sky", "bright"],
            &["#bfefff", "#2ab7ff", "#007ad9", "#004a9f"],
            "#021a40",
            "#ffffff",
        ),
        pal(
            "lapis",
            "Lapis Lazuli",
            "Blue",
            "Ultramarine stone with golden flecks",
            &["blue", "gem"],
            &["#3f5bff", "#2336c9", "#16218f", "#0c125c"],
            "#060a30",
            "#ffd24a",
        ),
        pal(
            "ice-crystal",
            "Ice Crystal",
            "Blue",
            "Frosted crystal: white, pale cyan, glacier blue",
            &["blue", "ice", "bright"],
            &["#ffffff", "#d8fbff", "#8ce8ff", "#3fb4ff", "#1070ff"],
            "#0a1a3a",
            "#ffffff",
        ),
        pal(
            "denim",
            "Denim",
            "Blue",
            "Worn indigo denim, faded to stonewash",
            &["blue", "soft"],
            &["#9bb4e8", "#5a7dcc", "#34539e", "#1c3470"],
            "#0a1430",
            "#dfe8ff",
        ),
        pal(
            "abyss",
            "Abyss",
            "Blue",
            "Bioluminescent sparks in the deepest ocean",
            &["blue", "dark", "ocean"],
            &["#00ffe0", "#0088ff", "#0a2a9a", "#03104a"],
            "#010622",
            "#00ffe0",
        ),
        // ---- Aqua / teal -------------------------------------------------------
        pal(
            "coral-reef",
            "Coral Reef",
            "Aqua",
            "Turquoise water over living coral",
            &["teal", "ocean", "warm"],
            &["#00e5d0", "#00b4d8", "#ff7f6e", "#ff4f6d"],
            "#032028",
            "#fff0e0",
        ),
        pal(
            "lagoon",
            "Lagoon",
            "Aqua",
            "Tropical lagoon turquoise",
            &["teal", "ocean"],
            &["#00ffc8", "#00e0c0", "#00b4d8", "#0077b6"],
            "#002a30",
            "#e0fff8",
        ),
        pal(
            "ice-mint",
            "Ice Mint",
            "Aqua",
            "Frosted mint and cool aqua",
            &["teal", "pastel"],
            &["#e0fff8", "#a0ffe0", "#40e0c0", "#00a0a0"],
            "#002020",
            "#ffffff",
        ),
        // ---- Purple ------------------------------------------------------------
        pal(
            "twilight",
            "Twilight",
            "Purple",
            "Cyan sky dissolving into violet night",
            &["purple", "blue"],
            &["#00f0ff", "#3a7bff", "#5a2bff", "#8a00ff"],
            "#0c0530",
            "#00f0ff",
        ),
        pal(
            "galaxy",
            "Galaxy",
            "Purple",
            "Deep space indigo with a blue-violet nebula",
            &["purple", "space"],
            &["#9a5cff", "#6a2cff", "#2f55ff", "#0a0a5a"],
            "#060a40",
            "#d8faff",
        ),
        pal(
            "amethyst",
            "Amethyst",
            "Purple",
            "Lavender to royal purple crystal",
            &["purple", "gem"],
            &["#e0b0ff", "#b060ff", "#7a20ff", "#4b0082"],
            "#12002a",
            "#ffe0ff",
        ),
        pal(
            "lavender",
            "Lavender",
            "Purple",
            "Soft lavender fields at dusk",
            &["purple", "pastel"],
            &["#efdcff", "#c9a8ff", "#9a7dff", "#6a5acd"],
            "#150a30",
            "#ffffff",
        ),
        // ---- Warm --------------------------------------------------------------
        pal(
            "sunrise",
            "Sunrise",
            "Warm",
            "First light: gold into rose into morning blue",
            &["warm", "blue", "sky"],
            &["#ffe07a", "#ffa36c", "#ff6f91", "#6f8cff"],
            "#180a28",
            "#fffbe0",
        ),
        pal(
            "sunset",
            "Sunset",
            "Warm",
            "Golden hour through magenta into dusk",
            &["warm", "orange", "pink"],
            &["#ffd000", "#ff7a00", "#ff2a6d", "#7a00ff"],
            "#200010",
            "#fff0a0",
        ),
        pal(
            "ember",
            "Ember",
            "Warm",
            "Glowing coals, amber to deep red",
            &["warm", "red", "fire"],
            &["#ffe080", "#ff8c00", "#ff3000", "#900000"],
            "#200000",
            "#ffffa0",
        ),
        pal(
            "sakura",
            "Sakura",
            "Warm",
            "Cherry blossom pinks",
            &["pink", "pastel"],
            &["#ffe4f0", "#ffb0d0", "#ff70a6", "#d63384"],
            "#200010",
            "#ffffff",
        ),
        // ---- Green -------------------------------------------------------------
        pal(
            "forest",
            "Forest",
            "Green",
            "Sunlit leaves down to the forest floor",
            &["green", "nature"],
            &["#b8ff60", "#40e040", "#008f4c", "#004020"],
            "#001a08",
            "#f0ffa0",
        ),
        pal(
            "matrix",
            "Matrix",
            "Green",
            "Phosphor-green terminal rain",
            &["green", "hacker"],
            &["#a0ffa0", "#00ff40", "#00a020", "#003010"],
            "#001000",
            "#e0ffe0",
        ),
        pal(
            "toxic",
            "Toxic",
            "Green",
            "Radioactive lime and acid green",
            &["green", "neon"],
            &["#e0ff00", "#80ff00", "#00ff60", "#00a060"],
            "#081000",
            "#ffffff",
        ),
        pal(
            "mint-chip",
            "Mint Chip",
            "Green",
            "Cool mint with dark chocolate chips",
            &["green", "pastel"],
            &["#d8fff0", "#98f5c8", "#3ddc97", "#1f7a55"],
            "#1a0e08",
            "#ffffff",
        ),
        // ---- Vivid combos ------------------------------------------------------
        pal(
            "vaporwave",
            "Vaporwave",
            "Vivid",
            "Pastel pink and cyan, straight from 1995",
            &["retro", "pastel", "pink"],
            &["#ff9ff3", "#c56cf0", "#7ed6ff", "#48dbfb"],
            "#140a28",
            "#ffffff",
        ),
        pal(
            "electric-storm",
            "Electric Storm",
            "Vivid",
            "Violet storm clouds split by cyan lightning",
            &["blue", "purple", "neon"],
            &["#e0ffff", "#00e5ff", "#5b2cff", "#1a0a6a"],
            "#07031e",
            "#ffffff",
        ),
        pal(
            "cyberpunk",
            "Cyberpunk",
            "Vivid",
            "Street-sign yellow, cyan and hot red",
            &["neon", "cyber"],
            &["#fcee09", "#00f0ff", "#ff003c"],
            "#100018",
            "#ffffff",
        ),
        pal(
            "synthwave",
            "Synthwave",
            "Vivid",
            "Outrun pinks and purples over a cyan horizon",
            &["retro", "neon", "pink"],
            &["#05d9e8", "#d300c5", "#ff2a6d", "#3a0ca3"],
            "#0a0520",
            "#ffffff",
        ),
        pal(
            "miami",
            "Miami Nights",
            "Vivid",
            "Retro pink, aqua and mint",
            &["retro", "pastel"],
            &["#ff71ce", "#b967ff", "#01cdfe", "#05ffa1"],
            "#100820",
            "#ffffff",
        ),
        pal(
            "fire-ice",
            "Fire & Ice",
            "Vivid",
            "Molten orange meeting glacier blue",
            &["blue", "fire", "contrast"],
            &["#ff3000", "#ff9000", "#ffffff", "#00b0ff", "#0030ff"],
            "#100010",
            "#ffffff",
        ),
        pal(
            "rainbow",
            "Rainbow",
            "Vivid",
            "The full spectrum",
            &["rainbow", "colourful"],
            &["#ff0000", "#ff8000", "#ffff00", "#00ff00", "#00ffff", "#0040ff", "#a000ff"],
            "#101010",
            "#ffffff",
        ),
        // ---- Soft --------------------------------------------------------------
        pal(
            "pearl",
            "Pearl",
            "Soft",
            "Soft whites with a cool blue sheen",
            &["white", "minimal"],
            &["#ffffff", "#e8f0ff", "#b0c4de", "#7090c0"],
            "#101828",
            "#ffffff",
        ),
        pal(
            "dawn",
            "Dawn",
            "Soft",
            "Peach sunrise over a pale blue sky",
            &["pastel", "warm", "blue"],
            &["#ffd8b0", "#ffb0c0", "#b0c8ff", "#7090ff"],
            "#101030",
            "#fff8f0",
        ),
        pal(
            "mono-blue",
            "Monochrome Blue",
            "Soft",
            "One blue, many brightnesses: calm and focused",
            &["blue", "minimal"],
            &["#9fb8ff", "#5c82ff", "#2f5bff", "#1a36b0", "#0c1a60"],
            "#050a24",
            "#d0dcff",
        ),
    ]
}
